### ISSUE TITLE
Sensor 

### ISSUE THREAD

**Issue by kassqaa** [marcin2x/DistributedMonitor#21]
1. Konfiguracja adresu Monitora oraz interwałów w pliku JSON
2. Obsługa komunikacji z Monitorem w wybranym protokole(TCP/IP)
3. Rejestracja Sensora w Monitorze
4. Unikalne ID Sensora (propozycja: adres MAC)
- przesłanie metadanych
- w określonych interwałach czasowych lub na starcie aplikacji (lepiej tylko na starcie, ale w razie problemów można w większych interwałach)
5. Zbieranie metryk CPU oraz RAM i przesłanie ich do Monitora (razem z ID)
- w określonych interwałach

**Comment by kassqaa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sensor](https://trello.com/c/smHABtZd/12-sensor)

**Comment by gremlingg7** [comment]
1. Cała konfiguracja znajduje się w pliku sensor_config.json
2. Przynajmniej lokalnie wysyła i odbiera dane
3. To po stronie monitora
4. W opisie https://github.com/marcin2x/DistributedMonitor/blob/master/docs/REST_API-Draft/TCPIP.md
jest coś o unikalności id dla różnych sensorów na tej samej maszynie, więc jest on generowany przy każdym uruchomieniu sensora
- metadane są przesyłane co określony interwał
5. j.w. zgodnie z https://github.com/marcin2x/DistributedMonitor/blob/master/docs/REST_API-Draft/TCPIP.md

**Comment by marcin2x** [comment]
Proszę stwórz pull request ze swojej gałęzi. Wtedy będę mógł przejrzeć kod, ewentualnie napisać jakieś uwagi i później dołączyć go do głównej gałęzi.
