### ISSUE TITLE
WebApp - Search

### ISSUE THREAD

**Issue by kassqaa** [marcin2x/DistributedMonitor#45]
Wyszukiwanie w hostach i zasobach (wymaganie 2)
 * użycie mechanizmu w stylu "LIKE" z języka SQL
 * @ - wyszukuj w hostach (np. '@Zeus' - wszystkie hosty z 'zeus' w nazwie)
 * \# - wyszukuj w zasobach (jw. ale dla zasobów)
 * wyszukiwanie ma być niewrażliwe na wielkość liter

**Comment by kassqaa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [WebApp - Search](https://trello.com/c/q9TshAFZ/22-webapp-search)

**Comment by kassqaa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [WebApp - Search](https://trello.com/c/q9TshAFZ/22-webapp-search)

**Comment by wojgrochola** [comment]
Funkcjonalność dodana według opisu. W momencie gdy Input search jest pusty, bądź zaczyna się od znaków różnych od @ # wtedy wyszukiwanie nie działa
