### ISSUE TITLE
WebApp - View

### ISSUE THREAD

**Issue by kassqaa** [marcin2x/DistributedMonitor#46]
Przerobienie widoku wykresu
 * przerobienie obecnego widoku na drzewko z checkboxami
 * możliwość wyświetlania wielu zasobów i sensorów jednocześnie
 * konfigurowalność interwału odświeżania

**Comment by kassqaa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [WebApp - View](https://trello.com/c/hidEKNje/23-webapp-view)

**Comment by barteq93** [comment]
Done:
- lista sensorów i zasobów w postaci rozwijanego drzewka z checkboxami
- checkbox na automatyczne odświeżanie wykresu + input na interwał w sekundach
