### ISSUE TITLE
WebApp - Archives

### ISSUE THREAD

**Issue by kassqaa** [marcin2x/DistributedMonitor#47]
Wykresy historyczne
 * dostęp do historycznych wykresów
 * możliwość sprecyzowania okna czasowego
 * wszystkie funkcjonalności jak w normalnym widoku wykresu (wyszukiwanie, checkboxy itd.)
 * eksport danych widocznych na wykresie do csv

**Comment by kassqaa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [WebApp - Archives](https://trello.com/c/MwkLYer1/24-webapp-archives)

**Comment by barteq93** [comment]
Done:
- dwa datepickery do ustawienia dat (z dokładnością do minuty) + przycisk do resetowania obu dat (po resecie dat wyświetlany jest wykres z ostatni pomiarami dla wybranych zasobów)
- archiwalne pomiary wyświetlane na wykresie po ustawieniu obu dat (po zamknięciu datepickera)
- auto-odświeżanie wykresu niedostępne gdy na wykresie są dane archiwalne
- przycisk do eksportu danych do pliku csv (dostępny zawsze gdy na wykresie są dane i auto-odświeżanie jest wyłączone)
