### ISSUE TITLE
WebApp - Add complex

### ISSUE THREAD

**Issue by kassqaa** [marcin2x/DistributedMonitor#48]
Tworzenie pomiaru złożonego
 * użytkownik może stworzyć pomiar złożony z wybranego pomiaru prostego (konkretny zasób dla konkretnego hosta)
 * pomiary złożone widoczne dla wszystkich użytkowników
 * typ: średnia, min, max
 * okno czasowe: w minutach
 * interwał: w minutach
 * obowiązkowa nazwa (unikalna dla danego hosta)
 * para (host, nazwa pomiaru złożonego) ma być unikalna

**Comment by kassqaa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [WebApp - Add complex](https://trello.com/c/RpKoEQX7/25-webapp-add-complex)

**Comment by totodot** [comment]
- [ ] **użytkownik może stworzyć pomiar złożony z wybranego pomiaru prostego (konkretny zasób dla konkretnego hosta)**
Tablica measurements dla hosta jest tablica wszystkich pomiarów ( zarówno złożonych jak i prostych). Nie ma tam uwzględnione jakiego typu jest to pomiar. Warto było by dodać taka informacje ponieważ teraz przy tworzeniu pomiary złożonego możemy wybrać jako measurement_id, id pomiaru złożonego.
- [x] pomiary złożone widoczne dla wszystkich użytkowników
- [x] typ: średnia, min, max
- [x] okno czasowe: w minutach
- [x] interwał: w minutach
- [x] obowiązkowa nazwa (unikalna dla danego hosta)
Sprawdzane przez api my wyświetlamy jedynie błąd jeżeli taki name juz istnieje.
- [x] para (host, nazwa pomiaru złożonego) ma być unikalna
Pytanie do API czy takie coś jest obsłużone?

**Comment by marcin2x** [comment]
1. Ok, to jest problem. Jako, że mamy mało czasu, to możemy umożliwić stworzenie pomiaru złożonego tylko dla pomiarów, które nazywają się "CPU" i "RAM".  Ewentualnie zmienić pobieranie danych hostów o dodatkowe pole.
2. Jest to obsłużone po stronie API i API powinno rzucić błąd w takiej sytuacji.
