### ISSUE TITLE
WebApp - Manage complex

### ISSUE THREAD

**Issue by kassqaa** [marcin2x/DistributedMonitor#49]
Zarządzanie pomiarami złożonymi
 * użytkownik ma dostęp do listy pomiarów złożonych
 * użytkownik może usunąć pomiar złożony stworzony przez siebie
 * brak możliwości edycji

**Comment by kassqaa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [WebApp - Manage complex](https://trello.com/c/OGoIiTRj/26-webapp-manage-complex)

**Comment by totodot** [comment]
Jedyne czego brakuje to usuwanie pomiarów złożonych stworzonych przez siebie. W tym momencie przycisk DELETE znajduje się przy każdym pomiarze nawet takim który nie jest stworzony przez nas. Jak pobieramy pomiary złożone jest tam pole user_id jednam po zalogowaniu my nie znamy swojego id. 
Logowanie zwraca nam jedynie jwt. Aby ukryć przycisk DELETE dla nie naszych pomiarów potrzebnym tam jest id aktualnie zalogowanego usera.

**Comment by marcin2x** [comment]
Możliwe, że konieczne będzie rozszerzenie API o zwrócenie user_id oprócz tokena JWT. Na tą chwilę operacja usunięcia jest zrobiona po stronie API.
Jako obejście problemu proponuje użycie user_id zwróconego z GET /monitors. Zwracamy tylko monitory dla danego użytkownika, więc powinno być ok.
