### ISSUE TITLE
Documentation - Installation guide

### ISSUE THREAD

**Issue by kassqaa** [marcin2x/DistributedMonitor#58]
Podręcznik instalacji
 * opis wymagań dla systemu (Python, Node.js, pip itd.)
 * opis instalacji (instalacja pakietów z pipa itd.)
 * opis konfiguracji (głównie komunikacji Sensor -> Monitor i WebApp -> Auth, tzn. adresy, porty itd.)

**Comment by kassqaa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Documentation - Installation guide](https://trello.com/c/9rrKKhtU/39-documentation-installation-guide)

**Comment by gremlingg7** [comment]
Napisałem co wiedziałem, wszelkie uwagi, zgłoszenia mile widziane
