### ISSUE TITLE
Defects - WebApp - Login

### ISSUE THREAD

**Issue by Justyna93** [marcin2x/DistributedMonitor#63]
- Podczas logowania przy podaniu błędnego maila (np. brak "@", lub brak znaków po "@") komunikat w przeciwieństwie do innych na tej stronie jest po polsku.

- każde odświeżenie strony już po zalogowaniu powraca do strony logowania

**Comment by Justyna93** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Defects - WebApp - Login](https://trello.com/c/YILUTTRK/41-defects-webapp-login)

**Comment by wojgrochola** [comment]
Jeśli mowa o tym komunikacie to pochodzi on od przeglądarki a nie bezpośrednio z naszej aplikacji. Dlatego język zależy od języka przeglądarki (albo systemu), u mnie w wersji angielskiej komunikaty sa po ang. Zamykam issue ;)
![tmp](https://cloud.githubusercontent.com/assets/15139231/26560073/f06aa14a-44b3-11e7-936a-d99c666f3154.png)
