### ISSUE TITLE
Defects - WebApp - add/delete monitor

### ISSUE THREAD

**Issue by Justyna93** [marcin2x/DistributedMonitor#64]
- po dodaniu monitora, okno nie znika

- trzeba odświeżyć stronę żeby zobaczyć nowo dodany monitor

- po próbie skasowania monitora, monitor nadal pozostaje

- podczas dodawania monitora i kliknięciu na "Simulate Error", nie symuluje błędu tylko dodaje monitor

- dodając monitor nie wysyła do niego requesta, nie sprawdza czy pod danym IP monitor istnieje

**Comment by Justyna93** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Defects - WebApp - add/delete monitor](https://trello.com/c/Uhk9vPta/42-defects-webapp-add-delete-monitor)

**Comment by totodot** [comment]
- [x]  po dodaniu monitora, okno nie znika 
 - [x] trzeba odświeżyć stronę żeby zobaczyć nowo dodany monitor 
 - [ ]  po próbie skasowania monitora, monitor nadal pozostaje
Próba usunięcia monitora z api powoduje błąd
Request: DELETE  http://52.174.179.132:8081/monitors/11
Response: 

> <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
> <title>404 Not Found</title>
> <h1>Not Found</h1>
> <p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>
 - [x]  podczas dodawania monitora i kliknięciu na "Simulate Error", nie symuluje błędu tylko dodaje monitor 
 - [x]  dodając monitor nie wysyła do niego requesta, nie sprawdza czy pod danym IP monitor istnieje 
`Moim zdaniem sprawdzeniem czy pod danym ip istnieje juz jakis monitor powinien zajmować się serwer (api). Jeżeli na takie ip został już dodany monitor to API powinno zwrócić błąd który wyświetlimy na front. Sprawdzanie tego po stronie frontu jest bez sensu. Co z tego, że ja zablokuje możliwość dodania monitora z ip który już istnieje, jeżeli użytkownik będzie mógł stuknąć taki request po API a monitor i tak się doda`

**Comment by marcin2x** [comment]
Błąd w usuwaniu - rozjazd pomiędzy implementacją API, a dokumentacją. Będzie poprawiony.

**Comment by marcin2x** [comment]
dokumentacja zaaktualizowana
