### ISSUE TITLE
Defects - WebApp - Data 

### ISSUE THREAD

**Issue by Justyna93** [marcin2x/DistributedMonitor#66]
- niektóre dane po najechaniu myszką na kropkę na wykresie wyświetlane są do drugiego bądź pierwszego miejsca po przecinku, a niektóre nie (np. 11.790000000000001), to samo w tabeli "Last measurements" -> należy ujednolicić wyświetlanie danych

**Comment by Justyna93** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Defects - WebApp - Data](https://trello.com/c/jFUwg2k0/44-defects-webapp-data)

**Comment by totodot** [comment]
Poprawione
